blank_issues_enabled: false

contact_links:
  - name: Myyaml | YAML for Modern C/C++ ğŸ“š
    url: https://github.com/djoezeke/myyaml
    about: Simple and Fast Yaml Ain't a Markup Language (YAML) Parser for Modern C/C++.

  - name: Myyaml Discussions ğŸ’–
    url: https://github.com/djoezeke/myyaml/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Myyaml Issues | Bug Bounty ğŸ
    url: https://github.com/djoezeke/myyaml/issues
    about: Please report issues and vulnerabilities here.

  - name: Myyaml Releases & Tags ğŸ“¦
    url: https://github.com/djoezeke/myyaml/releases
    about: Please latest Myyaml release here.

  - name: Myyaml Documentation ğŸ“š
    url: https://djoezeke.github.io/myyaml/
    about: Please refer to the Myyaml documentation here.
