name: Publish Documentation

# publish the documentation on every merge to main branch
on:
  push:
    branches: [main]
    paths: [docs/mkdocs/**]

  pull_request:
    branches: [main]
    paths: [docs/mkdocs/**]

  workflow_dispatch:

# we don't want to have concurrent jobs, and we don't want to cancel running jobs to avoid broken publications
concurrency:
  group: documentation
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  publish:
    name: Build & Publish Documentation to GitHub Pages.

    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./docs/mkdocs

    if: github.repository == 'djoezeke/myyaml'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build distributions & Docs
        run: |
          mkdocs build

      - name: Publish documentation ðŸ“š to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          # This token is automatically provided by GitHub Actions
          # and has the necessary permissions to push to gh-pages.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
